### ISSUE TITLE
Invalid characters ending up in Location header due to SAML redirect

### ISSUE THREAD

**Issue by cailyoung** [reportportal/service-authorization#292] opened 2023-11-27 22:23 UTC
https://github.com/reportportal/service-authorization/blob/b96cd43bbeb8194358861ac10a7d6597bbc08591/src/main/java/com/epam/reportportal/auth/AuthSuccessHandler.java#L58

Reported as https://github.com/reportportal/reportportal/issues/1989

We are observing this semi-regularly in our environment. As far as I can tell, the `Location` header is injected at the above point, and I do not know enough about Spring to know why there would be CRLF characters injected by Entra ID SAML SSO.

**Comment by alena-babrova** [comment] 2023-11-29 14:14
Hello @cailyoung,

I suppose that it is the similar issue as described in the following thread https://github.com/reportportal/reportportal/issues/1989.
If it is so, can we close the discussion as duplicate?

**Comment by cailyoung** [comment] 2023-12-04 05:56
It's up to you; the other issue is on an umbrella repo, this one is on the auth service itself. I don't mind either way.

**Comment by alena-babrova** [comment] 2023-12-11 11:42
Dear @cailyoung,
Yes, you are right that the issue is related to auth service but our community has already started the thread in the general repository.
I am closing the issue as duplicate.

**Closed by alena-babrova** 2023-12-11 11:42 UTC
